enum MHWParser {
	MHWParser_set_name,
	MHWParser_alpha_piece_1,
	MHWParser_alpha_piece_2,
	MHWParser_alpha_piece_3,
	MHWParser_alpha_piece_4,
	MHWParser_alpha_piece_5,
	MHWParser_beta_piece_1,
	MHWParser_beta_piece_2,
	MHWParser_beta_piece_3,
	MHWParser_beta_piece_4,
	MHWParser_beta_piece_5,
	MHWParser_bonus_2p,
	MHWParser_bonus_3p,
	MHWParser_bonus_4p,
	MHWParser_count,
};
